version: '3'

services:
  web:
    image: php:7.3-apache
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor
      - ./src:/var/www/src
    entrypoint: /bin/bash -c 'a2enmod rewrite; apache2-foreground'
